# -*- coding: utf-8 -*-
"""Automated_Data_Cleaning_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrwr4fl3k8FO8tSU0YsmASGWEMG65yR_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('diabetes_prediction_dataset.csv')

print(df.shape)
df.info()
print(df.isnull().sum())

df['gender'] = df['gender'].str.strip().str.lower()
df['gender'] = df['gender'].replace({
    'm':'male',
    'f':'female'
})


df = df[(df['age'] > 0) & (df['age'] < 115)]


sns.set_theme(style='whitegrid')

plt.figure(figsize=(8,6))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=0.5
)

plt.title('Medical Metric Correlation Matrix')
plt.tight_layout()

plt.savefig('correlation_heatmap.png', dpi=300)

plt.show()

df.to_csv(
    'cleaned_hospital_records.csv',
    index=False
)

print("Pipeline completed successfully!")